/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assyifacake.views.Transaksi;

import java.awt.Dimension;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author user
 */
public class LaporanPenjualan2 extends javax.swing.JFrame {

    /**
     * Creates new form LaporanPenjualan2
     */
    public LaporanPenjualan2() {
        initComponents();
        createFrame1();        

    }
    
    private void createFrame1() {
        
//        Runnable runnable = new Runnable() {
//            @Override
//            public void run() {
//                JLabel loading = new JLabel("Sedang memuat, harap menunggu",SwingConstants.CENTER);
//                loading.setSize(500,500);
//                loading.setAlignmentY(250);
//                jPanel1.add(loading);
//                final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//                dataset.addValue(34.0, "Penjualan/produk", "Kue Enak");
//                dataset.addValue(23.0, "Penjualan/produk", "Kue Enggak Enak");
//                dataset.addValue(54.0, "Penjualan/produk", "Kue Sultan");
//                final JFreeChart chart = ChartFactory.createBarChart(
//                    "", 
//                    "Produk",
//                    "Penjualan",
//                    dataset,
//                    PlotOrientation.VERTICAL,
//                    true,
//                    true,
//                    false
//                );
//                final ChartPanel chartPanel = new ChartPanel(chart);
//                chartPanel.setSize(500,500);
//                chartPanel.setPreferredSize(new Dimension(300, 300));
//                jPanel1.removeAll();
//                jPanel1.add(chartPanel);
//                chartPanel.setVisible(true);
//            }
//        };
        SwingWorker worker = new SwingWorker() {
            @Override
            protected ChartPanel doInBackground() throws Exception {
                JLabel loading = new JLabel("Sedang memuat, harap menunggu",SwingConstants.CENTER);
                loading.setSize(500,500);
                loading.setAlignmentY(250);
                jPanel1.add(loading);
                final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                dataset.addValue(34.0, "Penjualan/produk", "Kue Enak");
                dataset.addValue(23.0, "Penjualan/produk", "Kue Enggak Enak");
                dataset.addValue(54.0, "Penjualan/produk", "Kue Sultan");
                final JFreeChart chart = ChartFactory.createBarChart(
                    "", 
                    "Produk",
                    "Penjualan",
                    dataset,
                    PlotOrientation.VERTICAL,
                    true,
                    true,
                    false
                );
                final ChartPanel chartPanel = new ChartPanel(chart);
                chartPanel.setSize(500,500);
                chartPanel.setPreferredSize(new Dimension(300, 300));
                
                return chartPanel;
                        }
            
            @Override
            protected void done() {
                try {
                    ChartPanel chartPanel = (ChartPanel) get();
                    
                    jPanel1.removeAll();
                    jPanel1.add(chartPanel);
                    chartPanel.setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(LaporanPenjualan2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    Logger.getLogger(LaporanPenjualan2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        };
        
        worker.execute();
                
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                new LaporanPenjualan2().setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
